/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as verifierSol from "./Verifier.sol";
export type { verifierSol };
import type * as xxxVerifierSol from "./xxxVerifier.sol";
export type { xxxVerifierSol };
export type { AdrasteiaZkPayment } from "./AdrasteiaZkPayment";
